const languageList = {
  C: "c",
  "C-99": "c99",
  "C++": "cpp",
  "C++ 14": "cpp14",
  "C++ 17": "cpp17",
  PHP: "php",
  Perl: "perl",
  "Python 2": "python2",
  "Python 3": "python3",
  Ruby: "ruby",
  "GO Lang": "go",
  Scala: "scala",
  "Bash Shell": "bash",
  SQL: "sql",
  Pascal: "pascal",
  "C#": "csharp",
  "VB.Net": "vbn",
  Haskell: "haskell",
  "Objective C": "objc",
  Swift: "swift",
  Groovy: "groovy",
  Fortran: "fortran",
  Lua: "lua",
  TCL: "tcl",
  Hack: "hack",
  RUST: "rust",
  D: "d",
  Ada: "ada",
  Java: "java",
  "R Language": "r",
  "FREE BASIC": "freebasic",
  VERILOG: "verilog",
  COBOL: "cobol",
  Dart: "dart",
  YaBasic: "yabasic",
  Clojure: "clojure",
  NodeJS: "nodejs",
  Scheme: "scheme",
  Forth: "forth",
  Prolog: "prolog",
  Octave: "octave",
  CoffeeScript: "coffeescript",
  Icon: "icon",
  "F#": "fsharp",
  "Assembler - NASM": "nasm",
  "Assembler - GCC": "gccasm",
  Intercal: "intercal",
  Nemerle: "nemerle",
  Ocaml: "ocaml",
  Unlambda: "unlambda",
  Picolisp: "picolisp",
  SpiderMonkey: "spidermonkey",
  "Rhino JS": "rhino",
  CLISP: "clisp",
  Elixir: "elixir",
  Factor: "factor",
  Falcon: "falcon",
  Fantom: "fantom",
  Nim: "nim",
  Pike: "pike",
  SmallTalk: "smalltalk",
  "OZ Mozart": "mozart",
  LOLCODE: "lolcode",
  Racket: "racket",
  Kotlin: "kotlin",
  Whitespace: "whitespace",
  Erlang: "erlang",
  J: "jlang"
};
function addlist() {
  var select = document.getElementById("language");
  for (let key in languageList) {
    var option = document.createElement("option");
    option.text = key;
    option.value = languageList[key];
    select.add(option);
  }
}
